const SPOTIFY_CLIENT_SECRET = import.meta.env.VITE_SPOTIFY_CLIENT_SECRET;
const SPOTIFY_CLIENT_ID = import.meta.env.VITE_SPOTIFY_CLIENT_ID;

const SPOTIFY_ACCESS_TOKEN = "spotify_access_token__";
const SPOTIFY_CODE_VERIFY = "spotify_code_verifier";
export {
  SPOTIFY_CLIENT_ID,
  SPOTIFY_ACCESS_TOKEN,
  SPOTIFY_CODE_VERIFY,
  SPOTIFY_CLIENT_SECRET,
};
